name: Bundle Maven Quarkus Release

on: [workflow_dispatch]

jobs:
  call-workflow:
    uses: Forsakringskassan/.github/.github/workflows/bundle-maven-quarkus-release.yaml@main
    secrets:
      PACKAGES_RW_ACTOR: ${{ secrets.PACKAGES_RW_ACTOR }}
      PACKAGES_RW_TOKEN: ${{ secrets.PACKAGES_RW_TOKEN }}
